### ISSUE TITLE
Error Deploying with prisma 

### ISSUE THREAD

**Issue by s-kris** [netlify/netlify-plugin-nextjs#125]
**Describe the bug**
Prisma query engine not found when deployed with target:serverless. 

Build fails when using target: experimental-serverless-trace. 

Tried both ui installation and manual installation. 
 Looking forward to deploy my next js + prisma app to netlify. Thank you. 

More info:  
 https://github.com/prisma/prisma/issues/6051

**Versions**
- Next.js: 10.0.8
- plugin (if installed at fixed version):

**If you're using the CLI to build**
 - OS: [e.g. macOS, Windows]
 - netlify/cli version:

**If you're using file-based installation**
- netlify.toml:

**Comment by jlengstorf** [comment]
thanks for this, @s-kris! do you have a repo and/or build log we can look at? it will make chasing this down much faster

thank you!

**Comment by s-kris** [comment]
Sorry. I forgot to include the error for `target:serverless`. 

`Query engine binary for current platform "rhel-openssl-1.0.x" could not be found. This probably happens, because you built Prisma Client on a different platform. (Prisma Client looked in "/query-engine-rhel-openssl-1.0.x") Searched Locations: /.prisma/client /opt/build/repo/node_modules/@prisma/client / /var/task/node_modules/.prisma/client /var/task /var/task/node_modules/.prisma/client You already added the platforms "native", "rhel-openssl-1.0.x", "darwin" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal. Please create an issue at https://github.com/prisma/prisma-client-js/issues/new`

I opened this issue on prisma as well.

I will create minimal repo tomorrow and share it :)

**Comment by jlengstorf** [comment]
thank you!

**Comment by s-kris** [comment]
Hi @jlengstorf
Please find the minimal repo here: https://github.com/s-kris/test-prisma-netlify
You need to visit /api/prisma-test to see the error response.
Thank you for your patience. :)

**Comment by s-kris** [comment]
Looks like this has something to do with prisma

https://github.com/prisma/prisma/issues/6032

**Comment by jlengstorf** [comment]
thanks for following up with this @s-kris! we'll keep an eye on that Prisma issue

**Comment by jlengstorf** [comment]
this should be fixed as of Prisma 2.20.0! https://github.com/prisma/prisma/issues/6051#issuecomment-810085713

we confirmed it working, so I'll close this, but please let us know if you see it again!

**Comment by s-kris** [comment]
Hey @jlengstorf  the original error wasn't fixed. Here's the deployed url: https://60638a6d69433d000751b036--cocky-babbage-06fac3.netlify.app/api/prisma-test

Also, it says in he comment here: https://github.com/prisma/prisma/issues/6051#issuecomment-810085713 that original error still remains. Can you please share a sample repo if you got this working? It'd be really helpful.


sample repo: https://github.com/s-kris/test-prisma-netlify
branch: p2.20

**Comment by tjshipe** [comment]
Nice to see this was reopened as I'm also running into this same issue. I can't tell if it's a Prisma issue or Netlify because I deployed the same repo to Vercel without any issues.

**Comment by ascorbic** [comment]
Thanks for the report. I'm going to close this, because there is a new version of the plugin out which doesn't use experimental-serverless-trace. If you're still having trouble after upgrading, please could you open a new issue?
