### ISSUE TITLE
[Bug]: NEXTAUTH_URL is overridden

### ISSUE THREAD

**Issue by phbernard** [netlify/netlify-plugin-nextjs#1345]
### Summary

Because the plugin [supports NextAuth.js](https://github.com/netlify/netlify-plugin-nextjs/pull/1309), it [sets `NEXTAUTH_URL` automatically](https://github.com/netlify/netlify-plugin-nextjs/blob/346aad1a46e0e774b68d0436a193909689a6eb49/plugin/src/index.ts#L78) at deploy.

However, it does so every time, even when `NEXTAUTH_URL` is already explicitly initialized as a regular environment variable.

This behavior is misleading. Someone who sets `NEXTAUTH_URL` and doesn't know about NextAuth.js support has no reason to think `NEXTAUTH_URL` will be changed. It also blocks people who need to set `NEXTAUTH_URL` to a particular value (more about this below).

Suggested change:
- [When about to set `NEXTAUTH_URL`](https://github.com/netlify/netlify-plugin-nextjs/blob/346aad1a46e0e774b68d0436a193909689a6eb49/plugin/src/index.ts#L78), do nothing when it is already defined.
- Log this particular behavior so people who know about NextAuth.js support are not surprised.

As an aside, why would you want to explicitly set `NEXTAUTH_URL`? For example in case of multi-domains support. This can be achieved with multiple domains and a middleware. You can find an advanced example of this in the [Vercel Platform Starter Kit](https://github.com/vercel/platforms/blob/main/pages/_middleware.ts). A classic setting would be for the app to serve both example.com (+ www.example.com) and app.example.com. As the subdomain suggests, `NEXTAUTH_URL` will be set to https://app.example.com. Currently, the plugin just doesn't allow it.

### Steps to reproduce

I don't think this issue needs any guidance in this respect. The behavior is straightforward and fits in [5 lines of code.](https://github.com/netlify/netlify-plugin-nextjs/blob/346aad1a46e0e774b68d0436a193909689a6eb49/plugin/src/index.ts#L78)

### Plugin version

@netlify/plugin-nextjs@4.7.0 from Netlify app

### More information about your build

- [ ] I am building using the CLI
- [ ] I am building using file-based configuration (`netlify.toml`)

### Your netlify.toml file

<details>
  <summary>`netlify.toml`</summary>
  
```toml
# Paste content of your `netlify.toml` file here
```

</details>

### Your public/_redirects file

<details>
  <summary>`_redirects`</summary>
  
```toml
# Paste content of your `_redirects` file here
```

</details>

### Your `next.config.js` file

<details>
  <summary>`next.config.js`</summary>
  
```toml
# Paste content of your `next.config.js` file here. Check there is no private info in there.
```

</details>

### Builds logs (or link to your logs)

<details>
  <summary>Build logs</summary>
  
```
# Paste logs here
```

</details>

### Function logs

<details>
  <summary>Function logs</summary>
  
```
# Paste logs here
```

</details>

### .next JSON files

<details>
  <summary>generated .next JSON files</summary>
  
```
# Paste file contents here. Please check there isn't any private info in them
# You can either build locally, or download the deploy from Netlify by clicking the arrow next to the deploy time.
```

</details>

**Comment by ericapisani** [comment]
@phbernard Thanks so much for reporting this and for the explanation of the use case for explicitly setting the environment variable. 

I just merged a PR which should fix this, but if for some reason there's still issues around this functionality feel free to reach out.

**Comment by aleehedl** [comment]
@ericapisani I was wondering if `.env` files could be taken into account for this as well? I was still experiencing this bug until I found out from the pull request comments that `next.config.js` was the right place for setting the user-defined `NEXTAUTH_URL`. In my case, I write the values to `.env` file dynamically in the Netlify build step.
